### ISSUE TITLE
missing dependency gulp-babel

### ISSUE THREAD

**Issue by unphased** [jquense/react-widgets#201]
I have tried v0.12.7, 0.10.40, 0.10.32, OS X, Linux

Always I need to add the `gulp-babel` to the package.json. However it still doesnt allow `release` gulp task to complete. Perhaps I need to use a specific version of it.

```
/Users/steven/Documents/react-widgets/src/configure.js: Missing options in babel config: `extra.externalHelperPlugin`
    at NodePath.Plugin.visitor.Program (/Users/steven/Documents/react-widgets/node_modules/gulp-babel-helpers/node_modules/babel-plugin-external-helpers/index.js:26:17)
    at NodePath.call (/Users/steven/Documents/react-widgets/node_modules/babel-core/lib/traversal/path/context.js:56:28)
...
```

this also leaves the repo in a broken state with many (all?) source files taken out of lib.

```
$ git status --short
 D lib/Calendar.js
 D lib/Century.js
 D lib/Combobox.js
 D lib/ComboboxInput.js
 D lib/DateInput.js
 D lib/DateTimePicker.js
 D lib/Decade.js
 D lib/DropdownList.js
 D lib/Footer.js
 D lib/Header.js
 D lib/List.js
 D lib/ListGroupable.js
 D lib/ListOption.js
 D lib/Listbox.js
 D lib/Month.js
 D lib/Multiselect.js
 D lib/MultiselectInput.js
 D lib/MultiselectTagList.js
 D lib/NumberInput.js
 D lib/NumberPicker.js
 D lib/Popup.js
 D lib/ReplaceTransitionGroup.js
 D lib/SelectList.js
 D lib/SlideTransition.js
 D lib/TimeList.js
 D lib/WidgetButton.js
 D lib/Year.js
 D lib/configure.js
 D lib/fonts/rw-widgets.eot
 D lib/fonts/rw-widgets.svg
 D lib/fonts/rw-widgets.ttf
 D lib/fonts/rw-widgets.woff
 D lib/globalize-localizers.js
 D lib/img/loader-big.gif
 D lib/img/loading.gif
 D lib/index.js
 D lib/less/bootstrap-theme.less
 D lib/less/core.less
 D lib/less/datepicker.less
 D lib/less/icons.less
 D lib/less/mixins.less
 D lib/less/multiselect.less
 D lib/less/normalize.less
 D lib/less/popup.less
 D lib/less/react-widgets.less
 D lib/less/selectlist.less
 D lib/less/variables.less
 D lib/mixins/AriaDescendantMixin.js
 D lib/mixins/DataFilterMixin.js
 D lib/mixins/DataHelpersMixin.js
 D lib/mixins/ListMovementMixin.js
...
```

**Comment by jquense** [comment]
there is a bug further down, which I can't fix right now. for the meantime you can just npm i gulp-babel in the react-widgets directory if you want to build it yourself

**Comment by unphased** [comment]
When i try the `3.0.0-alpha.4` branch it seems like all gulp related dependencies have been taken out of `package.json`. Eventually it comes to `Error: Cannot find module './webpack.configs'`. I am hesitant about copying out the webpack config file from the master branch, but I do know that it is present in there.

**Comment by unphased** [comment]
Why is `lib-clean` even a thing? It runs and erases a ton of git tracked files.

**Comment by unphased** [comment]
I was able to run `dist-build` after removing the `['lib', 'dist-assets'],` part of the gulp task definition.

**Comment by jquense** [comment]
the 3.0 doesn't use gulp at all it should work just fine doing `npm run build` tho I am still reworking it all so here be dragons. and lib clean is a thing because all of lib is generated files.

**Comment by unphased** [comment]
Thanks for `npm run build` tip, that gets me to about here

```

> react-widgets@3.0.0-alpha.4 assets:dist /home/steven/react-widgets
> cpy src/img/* dist/img/ && cpy src/fonts/* dist/fonts/

Hash: f847d44b8ea27bc4495e
Version: webpack 1.12.2
Time: 17676ms
   [0] multi vendor 52 bytes {1} [built] [1 error]
    + 415 hidden modules

ERROR in multi vendor
Module not found: Error: Cannot resolve module 'globalize' in /home/steven/react-widgets
 @ multi vendor

ERROR in ./docs/components/docs.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ./pages/Combobox.api.md in /home/steven/react-widgets/docs/components
 @ ./docs/components/docs.jsx 23:15-49

ERROR in ./docs/components/docs.jsx
Module not found: Error: Cannot resolve module 'react-widgets-globalize-localizer' in /home/steven/react-widgets/docs/components
 @ ./docs/components/docs.jsx 41:49-93

ERROR in ./docs/components/docs.jsx
Module not found: Error: Cannot resolve module 'react-router/lib/HashHistory' in /home/steven/react-widgets/docs/components
 @ ./docs/components/docs.jsx 33:14-53

ERROR in ./docs/components/pages/DropdownList.api.md
Module not found: Error: Cannot resolve 'file' or 'directory' ../demos/DropdownList in /home/steven/react-widgets/docs/components/pages
 @ ./docs/components/pages/DropdownList.api.md 8:17-49

ERROR in ./docs/components/pages/SelectList.api.md
Module not found: Error: Cannot resolve 'file' or 'directory' ../demos/SelectList in /home/steven/react-widgets/docs/components/pages
 @ ./docs/components/pages/SelectList.api.md 8:17-47

ERROR in ./docs/components/pages/Calendar.api.md
Module not found: Error: Cannot resolve 'file' or 'directory' ../demos/Calendar in /home/steven/react-widgets/docs/components/pages
 @ ./docs/components/pages/Calendar.api.md 8:17-45

ERROR in ./docs/components/pages/Multiselect.api.md
Module not found: Error: Cannot resolve 'file' or 'directory' ../demos/Multiselect in /home/steven/react-widgets/docs/components/pages
 @ ./docs/components/pages/Multiselect.api.md 8:17-48

ERROR in ./docs/components/pages/NumberPicker.api.md
Module not found: Error: Cannot resolve 'file' or 'directory' ../demos/NumberPicker in /home/steven/react-widgets/docs/components/pages
 @ ./docs/components/pages/NumberPicker.api.md 8:17-49

ERROR in ./docs/components/demos/DateTimePicker.jsx
Module not found: Error: Cannot resolve module 'globalize/lib/cultures/globalize.culture.en-GB' in /home/steven/react-widgets/docs/components/demos
 @ ./docs/components/demos/DateTimePicker.jsx 11:0-57

ERROR in ./docs/components/demos/DateTimePicker.jsx
Module not found: Error: Cannot resolve module 'globalize/lib/cultures/globalize.culture.es' in /home/steven/react-widgets/docs/components/demos
 @ ./docs/components/demos/DateTimePicker.jsx 12:0-54

ERROR in ./docs/components/demos/DateTimePicker.jsx
Module not found: Error: Cannot resolve module 'globalize/lib/cultures/globalize.culture.fr' in /home/steven/react-widgets/docs/components/demos
 @ ./docs/components/demos/DateTimePicker.jsx 13:0-54

ERROR in ./docs/components/demos/DateTimePicker.jsx
Module not found: Error: Cannot resolve module 'globalize/lib/cultures/globalize.culture.ar-AE' in /home/steven/react-widgets/docs/components/demos
 @ ./docs/components/demos/DateTimePicker.jsx 14:0-57

> react-widgets@3.0.0-alpha.4 assets:docs /home/steven/react-widgets
> cpy node_modules/babel-core/browser.min.js docs/vendor
```
