### ISSUE TITLE
Cannot find module 'envify' from '.../node_modules/react-widgets' (v3.1.7 only)

### ISSUE THREAD

**Issue by philster** [jquense/react-widgets#321]
I'm trying to build a browserify bundle and got the following error (Note: I replaced the absolute path with `<path>`)
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'envify' from '<path>/node_modules/react-widgets'
    at <path>/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:46:17
    at process (<path>/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:173:43)
    at ondir (<path>/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:188:17)
    at load (<path>/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:69:43)
    at onex (<path>/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:92:31)
    at <path>/node_modules/browserify/node_modules/module-deps/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

This error did not exist on v3.1.6 and older.

**Comment by jquense** [comment]
dup #308

**Comment by philster** [comment]
Can we have this in the react-widgets documentation somewhere? It will be beneficial especially for users like me who don't use `envify` in my code but will need to include that dependency due to react-widgets.

**Comment by jquense** [comment]
the next version will include envify in dependencies so there is no need to do anything on your part. If you use browserify it will just work, if you don't it will just be transparent.
