### ISSUE TITLE
Custom wrapper around list in dropdown

### ISSUE THREAD

**Issue by kazagkazag** [jquense/react-widgets#571]
It is possible to add support for providing custom element in which `.rw-list` will be rendered? Something like `itemComponent`, but for entire list? 

Because now, when I have 100 items in dropdown, the list very high... I can style `.rw-list` and add `max-height`, but then scrollbar appears, and my client don't like native scrollbars. I have to implement custom scrollbar (:(), but I can't do it right now with this plugin...

**Comment by jquense** [comment]
There is a listComponent you can use to extend or change the list rendering. Its a more advanced feature that isn't really documented well. You can read through the source code tho for some insight

**Comment by kazagkazag** [comment]
Well, Ok, so I figured out, that you use provided listComponent or ./lib/List. So I decided to create HOC:

```jsx
function addScroll(BaseComponent) {
  return function (props, context) {
    return <MyScroll><BaseComponent {...props} {...context}/></MyScroll>;
  };
}

// and in my CustomSelect.jsx:

import List from "react-widget/lib/List"

export function CustomSelect(props) {
    return (
        <DropdownList
            listComponent={addScroll(List)}
           ...other props
       />
}
```

But I got error: 

```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at eval (eval at <anonymous> (http://localhost:3000/main.js:6049:2), <anonymous>:61:32)
    at Array.reduce (native)
    at Object.omitOwnProps (eval at <anonymous> (http://localhost:3000/main.js:6049:2), <anonymous>:60:23)
    at Constructor.render (eval at <anonymous> (http://localhost:3000/main.js:6013:2), <anonymous>:299:44)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (eval at <anonymous> (http://localhost:3000/main.js:3068:2), <anonymous>:687:34)
    at ReactCompositeComponentWrapper._renderValidatedComponent (eval at <anonymous> (http://localhost:3000/main.js:3068:2), <anonymous>:707:32)
    at ReactCompositeComponentWrapper.wrapper [as _renderValidatedComponent] (eval at <anonymous> (http://localhost:3000/main.js:2714:2), <anonymous>:66:21)
    at ReactCompositeComponentWrapper.performInitialMount (eval at <anonymous> (http://localhost:3000/main.js:3068:2), <anonymous>:291:30)
    at ReactCompositeComponentWrapper.mountComponent (eval at <anonymous> (http://localhost:3000/main.js:3068:2), <anonymous>:222:21)
```

And I don't have idea why... Can you just provide my some tip? Or example, how to use listComponent ?

**Comment by jquense** [comment]
its because the widgets expect `propTypes` to be defined on a list. you need to forward a few instance methods and at least do `MyList.propTypes = List.propTypes`

**Comment by kazagkazag** [comment]
Well, ok, so I decided to extend List component:

```jsx
import React from "react";
import List from "react-widgets/lib/List";
import Scrollbar from "../scrollbar/Scrollbar";

class ListWithScrollbar extends List {
    render() {
        return (
            <Scrollbar>
                {super.render()}
            </Scrollbar>
        );
    }
}

ListWithScrollbar.propTypes = List.propTypes;

export default ListWithScrollbar;
```

This is not the "react way", but still better than forwarding some methods, because I don't want to relay on undocumented implementation details. Now it works fine.

**Comment by jquense** [comment]
FYI this should be a bit easer and not require the List extension in v4
