### ISSUE TITLE
Error loading images and fonts

### ISSUE THREAD

**Issue by estibalizfraguas** [jquense/react-widgets#741]
Hello, 

I'm trying to use 'react-widgets' library but i've got problems while adding the styles. I've made the import and defined the fonts and images variables as specified like this at my initial sass file:

 ```
  $font-path: '~react-widgets/lib/fonts';
  $img-path: '~react-widgets/lib/img';

  @import '~react-widgets/lib/scss/react-widgets';
```

Also, added the 'url-loader' for the fonts and images at my webpack file and it ended up looking like this:

```
var app_root = 'src'; 
var path = require('path');
var CleanWebpackPlugin = require('clean-webpack-plugin');

module.exports = {
  app_root: app_root,
  entry: [
    'webpack-dev-server/client?http://localhost:8081',
    'webpack/hot/only-dev-server',
    'babel-polyfill',
    __dirname + '/' + app_root + '/index.js',
  ],
  output: {
    path: __dirname + '/public/js',
    publicPath: 'js/',
    filename: 'bundle.js',
  },
  debug: true,
  devtool: "#eval-source-map",
  module: {
    loaders: [
      {
        test: /\.js$/,
        loaders: ['react-hot', 'babel', 'eslint-loader', 'babel-loader'],
        exclude: /node_modules/,
      },
      {
        test: /\.scss$/,
        loaders: ['style', 'css', 'sass'],
      },
      {
        test: /\.css$/,
        loaders: ['style', 'css'],
      },
      {
         test: /\\.(gif|ttf|eot|svg|woff2?)$/, 
         use: 'url-loader?name=[name].[ext]' 
      },
    ],
  },
  devServer: {
    contentBase: __dirname + '/public',
  },
  plugins: [
    new CleanWebpackPlugin(['css/main.css', 'js/bundle.js'], {
      root: __dirname + '/public',
      verbose: true,
      dry: false,
    }),
  ],
};
```
But when I try to start my project it launchs an error like this, but for each img and font used at the library:

```
ERROR in ./~/react-widgets/lib/fonts/rw-widgets.eot
Module parse failed: /project/node_modules/react-widgets/lib/fonts/rw-widgets.eot Unexpected character ' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character ' (1:0)
    at Parser.pp$4.raise (/project/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/project/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/project/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/project/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/project/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/project/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/project/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/project/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/project/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/project/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
 @ ./~/css-loader!./~/sass-loader!./src/assets/scss/app.scss 6:33223-33272
```
I've tried almost everything without success. Am I missing something?

Thanks in advance,

Estíbaliz.

**Comment by jquense** [comment]
I think the webpack config is wrong you have an extra `\` escaping the font test, should be `test: /\.(gif|ttf|eot|svg|woff2?)$/`, you might always wnat to try something like https://github.com/jquense/webpack-atoms

**Comment by darrenklein** [comment]
@jquense Thank you so much for this fabulous library!

Regarding the OP's issue, the typo that you pointed out is in your docs at https://jquense.github.io/react-widgets/

```
    {
      test: /\\.(gif|ttf|eot|svg|woff2?)$/,
      use: 'url-loader?name=[name].[ext]',
    },
```

It looks to me like you may have the extra escape backslashes on the other loaders as well. Hope this is helpful!

**Comment by robwasmann** [comment]
Uhg yes, spent a few hours trying to figure out why the css wasn't loading. It was these extra slashes.
