### ISSUE TITLE
IE11 not supported for datetime picker 

### ISSUE THREAD

**Issue by waynebrantley** [jquense/react-widgets#774]
Go to your demo site for date time picker
http://jquense.github.io/react-widgets/api/DateTimePicker/

You will see a syntax error.

Also, does not display correctly - as shown on this ticket.
https://github.com/jquense/react-widgets/issues/685

**Comment by jquense** [comment]
I don't have IE11 readily available what is the syntax error?

**Comment by waynebrantley** [comment]
On your demo site, it is from 
https://github.com/gatsbyjs/gatsby

```
/***/ "./node_modules/gatsby-module-loader/index.js?name=component---src-layouts-index-js!./.cache/layouts/index.js":
/***/ (function(module, exports, __webpack_require__) {

module.exports = () => __webpack_require__.e/* import() */("component---src-layouts-index-js").then(__webpack_require__.bind(null, "./node_modules/babel-loader/lib/index.js?{\"presets\":[[\"/Users/jason/src/react-widgets/node_modules/babel-preset-jason/index.js\",{\"debug\":false,\"targets\":{\"browsers\":[\"> 1%\",\"last 4 versions\",\"not ie < 9\"]}}],[\"/Users/jason/src/react-widgets/www/node_modules/babel-preset-env/lib/index.js\",{\"loose\":true,\"uglify\":true,\"modules\":\"commonjs\",\"targets\":{\"browsers\":[\"> 1%\",\"last 2 versions\",\"IE >= 9\"]},\"exclude\":[\"transform-regenerator\",\"transform-es2015-typeof-symbol\"]}],\"/Users/jason/src/react-widgets/www/node_modules/babel-preset-stage-0/lib/index.js\",\"/Users/jason/src/react-widgets/www/node_modules/babel-preset-react/lib/index.js\"],\"plugins\":[\"/Users/jason/src/react-widgets/www/node_modules/babel-plugin-remove-graphql-queries/index.js\",\"/Users/jason/src/react-widgets/node_modules/babel-plugin-transform-decorators-legacy/lib/index.js\",\"/Users/jason/src/react-widgets/www/node_modules/babel-plugin-transform-object-assign/lib/index.js\"],\"cacheDirectory\":true}!./node_modules/css-literal-loader/lib/loader.js?{\"extension\":\".less\",\"tagName\":\"less\"}!./node_modules/imports-loader/index.js?define=>false,__VERSION__=>\"4.1.0\"!./.cache/layouts/index.js"))

/***/ }),
```

So - that is a demo site issue.  However, even if you solve that - the actual component is also broken.  When clicking on the button to bring up a calendar:

```
The above error occurred in the <MonthView> component:
    in MonthView (at Calendar.js:466)
    in Transition (at SlideTransitionGroup.js:58)
    in SlideTransition (at SlideTransitionGroup.js:125)
    in div (created by TransitionGroup)
    in TransitionGroup (at SlideTransitionGroup.js:120)
    in SlideTransitionGroup (at Calendar.js:465)
    in div (at Widget.js:35)
    in Widget (at Calendar.js:440)
    in Calendar (created by Uncontrolled(Calendar))
    in Uncontrolled(Calendar) (at DateTimePicker.js:433)
    in StaticContainer (at Popup.js:54)
    in div (at SlideDownTransition.js:108)
    in div (at SlideDownTransition.js:99)
    in Transition (at SlideDownTransition.js:87)
    in SlideDownTransition (at Popup.js:48)
    in Popup (at DateTimePicker.js:427)
    in div (at Widget.js:35)
    in Widget (at DateTimePicker.js:522)
    in DateTimePicker (created by Uncontrolled(DateTimePicker))
    in Uncontrolled(DateTimePicker)
    in div
    in div
    in Unknown (created by ConnectedField)
    in Connect
TypeError: Unable to get property 'map' of undefined or null reference
   {
      [functions]: ,
      __proto__: { },
      description: "Unable to get property 'map' of undefined or null reference",
      message: "Unable to get property 'map' of undefined or null reference",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Unable to get property 'map' of undefined or null reference
   at renderHeaders (http://localhost:8080/scripts/dist/main-client.js:49487:5)
   at render (http://localhost:8080/scripts/dist/main-client.js:49512:5)
   at finishClassComponent (http://localhost:22956/node_modules/react-dom/umd/react-dom.development.js:8415:7)
   at updateClassComponent (http://localhost:22956/node_modules/react-dom/umd/react-dom.development.js:8392:5)
   at beginWork (http://localhost:22956/node_modules/react-dom/umd/react-dom.development.js:8767:9)
   at performUnitOfWork (http://localhost:22956/node_modules/react-dom/umd/react-dom.development.js:10766:5)
   at workLoop (http://localhost:22956/node_modules/react-dom/umd/react-dom.development.js:10830:9)
   at callCallback (http://localhost:22956/node_modules/react-dom/umd/react-dom.development.js:580:9)",
      Symbol(react.element)_m.pyzlizc2dok: undefined
   }

SCRIPT5007: Unable to get property 'map' of undefined or null reference

```

Looking at the code - when this is called on IE ``week`` is undefined

```
 var _proto = MonthView.prototype;

  _proto.renderHeaders = function renderHeaders(week, format, culture) {
    var firstOfWeek = _localizers.date.firstOfWeek(culture);

    return week.map(function (date) {
      return _react.default.createElement("th", {
        className: "rw-head-cell",
        key: 'header_' + _dates.default.weekday(date, undefined, firstOfWeek),
        __source: {
          fileName: _jsxFileName,
          lineNumber: 38
        },
        __self: this
      }, _localizers.date.format(date, format, culture));
    });
  };

```

This line is called
``var month = _dates.default.visibleDays(focused, culture);``
On IE11 when the field is blank, focused is 'invalid date' and culture is undefined

We load our input with "1/1/2017' as a string and on Chrome this works fine.
However on IE this results in invalid date.
Loading the input with 1/1/2017 as a date makes the control work.

So, when your control has an 'invalid date' as the date to pick from - it gives the map error.  (This may happen on all browsers)    Of course, I am able to change to a real date to get rid of the invalid date issue and get what I have working, but thought you may want to fix this.

**Comment by waynebrantley** [comment]
Being forced on IE to provide the initial date as an actual date object causes numerous other problems for us.  Wonder why specifying a date as a string works on Chrome but not IE?

**Comment by jquense** [comment]
Chrome is probably parsing it implicitly. How are you providing the initial value? via react a string is not supported really for any browser, `value` and `defaultValue` are supposed to be Dates.

**Comment by waynebrantley** [comment]
This issue is all around the component erasing 'bad dates'.  When the user types in a date - it erases it. I discussed this on other threads with you.  Anyway, we use redux-forms and store the value in redux from your control as a string - this allows us to keep whatever they type.   The string is in redux - so your control just works with 'strings' when in Chrome....

Erasing the input is just not something that is works for us.

**Comment by jquense** [comment]
I'm not sure why using a string here works, but the component expects a Date as the value, it's likely to cause issues in other places trying to do this...which is to say it's an accident that it works at all. My instinct is that IE is doing the correct thing and failing.

Like I said in https://github.com/jquense/react-widgets/issues/725 I
m open to changing or making the current behavior configurable, but it's not a priority for _me_ I'd happily take a PR
