### ISSUE TITLE
Install development version of react-widgets into project

### ISSUE THREAD

**Issue by sators** [jquense/react-widgets#794]
I'm trying to create a build of react-widgets from my development version from pull request #793 as opposed to waiting for a new release but hitting hard walls...

I can get the library pulled into the project, but then keep hitting the below whenever I try to import it:

```
Uncaught TypeError: (0 , _reactLifecyclesCompat.default) is not a function
    at Object.<anonymous> (node_modules/react-widgets/lib/DropdownList.js:102:55)
    at Object.<anonymous> (node_modules/react-widgets/lib/DropdownList.js:723:3)
    at Module._compile (module.js:569:30)
```

It's quite confusing because reactLifecyclesCompat is not a required dependency...and it's not even in the project at all.  If I install straight from npm it works just fine...I don't understand what is different.  I'm running the build script to generate the build...

Any suggestions would be greatly appreciated...

**Comment by sators** [comment]
Looks like the local build is different than the CI build output, so I ended up doing an npm install, then dropping my changes ontop of that, and using that in my project.  #yeesh.
